/**
 * Pool Registry for DEX pools across multiple protocols.
 * Maps coin type pairs to their respective pool IDs on Bluefin, Cetus, and MMT.
 */

export type ProtocolPoolIds = {
  bluefin?: string;
  cetus?: string;
  mmt?: string;
};

/**
 * Creates a canonical key from two coin types by sorting them alphabetically.
 * This ensures the same key is returned regardless of the order of coin types.
 */
export function getCanonicalPairKey(
  coinTypeA: string,
  coinTypeB: string,
  fixCoinTypes?: boolean,
): string {
  if (fixCoinTypes && fixCoinTypes === true) {
    return [coinTypeA, coinTypeB].join('-');
  }
  return [coinTypeA, coinTypeB].sort((a, b) => b.localeCompare(a)).join('-');
}

/**
 * Pool registry mapping canonical coin pair keys to protocol pool IDs.
 * Keys are generated by sorting coin types alphabetically and joining with '|'.
 */
export const POOL_REGISTRY: Record<string, ProtocolPoolIds> = {
  [getCanonicalPairKey(
    '0x44f838219cf67b058f3b37907b655f226153c18e33dfcd0da559a844fea9b1c1::usdsui::USDSUI',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0x3fe620cd2b94ed7bc333f46e984cdea6cf42cfd9ddd54f15016d61c2f8149a90',
    cetus: '0xa7417fb5f59e23b0a7826d78f025653823c49265be07bbf6dd9e553ba4249a56',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0x2053d08c1e2bd02791056171aab0fd12bd7cd7efad2ab8f6b9c8902f14df2ff2::ausd::AUSD',
  )]: {
    bluefin: '0xb30df44907da6e9f3c531563f19e6f4a203d70f26f8a33ad57881cd7781e592d',
    cetus: '0x4811c1f0cc996e1b8f5befbf91fe4652bd6ff79115f09391ba157b21820fc9c0',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0x27792d9fed7f9844eb4839566001bb6f6cb4804f66aa2da6fe1ee242d896881::coin::COIN',
  )]: {
    bluefin: '0xe71aa89df60e737f1b687f8dfbd51e2a9b35706e9e5540ce9b053bd53fcb9ec3',
    cetus: '0xe0c526aa27d1729931d0051a318d795ad0299998898e4287d9da1bf095b49658',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0x356a26eb9e012a68958082340d4c4116e7f55615cf27affcff209cf0ae544f59::wal::WAL',
  )]: {
    bluefin: '0x41dcd6735e948e80b458d2007ca4fb90f9738b503e66572b6ef2f3d61fb9ada3',
    cetus: '0x72f5c6eef73d77de271886219a2543e7c29a33de19a6c69c5cf1899f729c3f17',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0x356a26eb9e012a68958082340d4c4116e7f55615cf27affcff209cf0ae544f59::wal::WAL',
    true,
  )]: {
    bluefin: '0x41dcd6735e948e80b458d2007ca4fb90f9738b503e66572b6ef2f3d61fb9ada3',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0x375f70cf2ae4c00bf37117d0c85a2c71545e6ee05c4a5c7d282cd66a4504b068::usdt::USDT',
  )]: {
    cetus: '0x84fc1515fd3d2395b2d67b301dc2b60040e31af7e295f8731c84bd528733252f',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0x3e8e9423d80e1774a7ca128fccd8bf5f1f7753be658c5e645929037f7c819040::lbtc::LBTC',
  )]: {
    bluefin: '0xa0153768c7ed857ffd8bad4708da873fb7825a6878e5f4c83f5df4c091933e56',
    cetus: '0x2fc6ee9183d0f1ca0d2dded02c416be6f4671bb82db55c26ce12b536812a4b8e',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0x5145494a5f5100e645e4b0aa950fa6b68f614e8c59e17bc5ded3495123a79178::ns::NS',
  )]: {
    cetus: '0x763f63cbada3a932c46972c6c6dcf1abd8a9a73331908a1d7ef24c2232d85520',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0x549e8b69270defbfafd4f94e17ec44cdbdd99820b33bda2278dea3b9a32d3f55::cert::CERT',
  )]: {
    bluefin: '0xbce4869d39b5247bbd25653a0b8f2143ed08ae963f1e9634abd3ef6b8f487a9e',
    cetus: '0x6c545e78638c8c1db7a48b282bb8ca79da107993fcb185f75cedc1f5adb2f535',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN',
  )]: {
    cetus: '0xcf994611fd4c48e277ce3ffd4d4364c914af2c3cbb05f7bf6facd371de688630',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0x06864a6f921804860930db6ddbe2e16acdf8504495ea7481637a1c8b9a8fe54b::cetus::CETUS',
  )]: {
    cetus: '0x2e041f3fd93646dcc877f783c1f2b7fa62d30271bdef1f21ef002cebf857bded',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0x7016aae72cfc67f2fadf55769c0a7dd54291a583b63051a5ed71081cce836ac6::sca::SCA',
  )]: {
    cetus: '0xaa72bd551b25715b8f9d72f226fa02526bdf2e085a86faec7184230c5209bb6e',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0x76cb819b01abed502bee8a702b4c2d547532c12f25001c9dea795a5e631c26f1::fud::FUD',
  )]: {
    cetus: '0xfc6a11998f1acf1dd55acb58acd7716564049cfd5fd95e754b0b4fe9444f4c9d',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xa99b8952d4f7d947ea77fe0ecdcc9e5fc0bcab2841d6e2a5aa00c3044e5544b5::navx::NAVX',
  )]: {
    bluefin: '0xac3f2181f453b68e540d3d7d1bf548fe3fc4f4164c4cdae7838c186c737be2f6',
    cetus: '0x0254747f5ca059a1972cd7f6016485d51392a3fde608107b93bbaebea550f703',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xaafb102dd0902f5055cadecd687fb5b71ca82ef0e0285d90afde828ec58ca96b::btc::BTC',
  )]: {
    bluefin: '0xd7d53e235c8a1db5e30bbde563053490db9b876ec8752b9053fee33ed845843b',
    cetus: '0x0fb4ad0e4c2c2b0a45d3f7bc5585cc9cea8486a63e4ef5cb768ddd9414fbb97a',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xaf8cd5edc19c4512f4259f0bee101a40d41ebed738ade5874359610ef8eeced5::coin::COIN',
  )]: {
    cetus: '0xc51752c87e7363dec32bb429cabcb7774aaabb45fa5d2c17edfbb59bd6d1deb0',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xb7844e289a8410e50fb3ca48d69eb9cf29e27d223ef90353fe1bd8e27ff8f3f8::coin::COIN',
  )]: {
    bluefin: '0x934b80a8fd75a1686ae90d09441774cc04d46916fc3ccb8bfe84a74f046802af',
    cetus: '0xf45b01f23e9951e37733b76c8cc7d22dcd23141aa246a86e17595a7aca610e1d',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xbde4ba4c2e274a60ce15c1cfff9e5c42e41654ac8b6d906a57efa4bd3c29f47d::hasui::HASUI',
  )]: {
    cetus: '0x871d8a227114f375170f149f7e9d45be822dd003eba225e83c05ac80828596bc',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xce7ff77a83ea0cb6fd39bd8748e2ec89a3f41e8efdc3f4eb123e0ca37b184db2::buck::BUCK',
  )]: {
    bluefin: '0xe63329f43a9474d421be85ff270bafc04667b811d215d4d4ee2512bcf2713896',
    cetus: '0x59cf0d333464ad29443d92bfd2ddfd1f794c5830141a5ee4a815d1ef3395bf6c',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xd0e89b2af5e4910726fbcd8b8dd37bb79b29e5f83f7491bca830e94f7f226d29::eth::ETH',
  )]: {
    bluefin: '0x788e945ce279153de07a6d392406487539060ee3d28046beb35c3024559ef863',
    cetus: '0x7079378d20cb521acc9a77c0d69da0e4b65cc07b2a1666868c95444939c3929e',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xd1b72982e40348d069bb1ff701e634c117bb5f741f44dff91e472d3b01461e55::stsui::STSUI',
  )]: {
    bluefin: '0x4746414e445cebdc19666b6e4de9b79a46ca7bcaa894bf10ec230e649376356e',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0x3b585786b13af1d8ea067ab37101b6513a05d2f90cfe60e8b1d9e1b46a63c4fa',
    cetus: '0xb8d7d9e66a60c239e7a60110efcf8de6c705580ed924d0dde141f4a0e2c90105',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xdeeb7a4662eec9f2f3def03fb937a663dddaa2e215b8078a284d026b7946c270::deep::DEEP',
  )]: {
    bluefin: '0x1b06371d74082856a1be71760cf49f6a377d050eb57afd017f203e89b09c89a2',
    cetus: '0xe01243f37f712ef87e556afb9b1d03d0fae13f96d324ec912daffc339dfdcbd2',
    mmt: '0x9b06ea8e1a0ee5c86f0b47512a3337e3c9c4e235c4ec698d15b51b0a8ec3e5a9',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xe1b45a0e641b9955a20aa0ad1c1f4ad86aad8afb07296d4085e349a50e90bdca::blue::BLUE',
  )]: {
    bluefin: '0xde705d4f3ded922b729d9b923be08e1391dd4caeff8496326123934d0fb1c312',
    cetus: '0xde016b9e743142fa66783611434d6bc35b78b51ceb9fe574d0d00e71e41d01d7',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xe44df51c0b21a27ab915fa1fe2ca610cd3eaa6d9666fe5e62b988bf7f0bd8722::musd::MUSD',
  )]: {
    bluefin: '0x66e1ed3181accbd954c74b5276a85f34ef71a5c2ad3e40b0ab2c3bcc8324632a',
    cetus: '0x7da922f6ebc9a5a83668fd1078f257d636a61ff78c7c55aeeca42e1efdf007fc',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xfa7ac3951fdca92c5200d468d31a365eb03b2be9936fde615e69f0c1274ad3a0::BLUB::BLUB',
  )]: {
    cetus: '0x40a372f9ee1989d76ceb8e50941b04468f8551d091fb8a5d7211522e42e60aaf',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xfe3afec26c59e874f3c1d60b8203cb3852d2bb2aa415df9548b8d688e6683f93::alpha::ALPHA',
  )]: {
    bluefin: '0xdc2482bdecb5237cba36332d5dea4204fb7df077fbf7b50054d24a678e0f61c9',
    cetus: '0xda7347c3192a27ddac32e659c9d9cbed6f8c9d1344e605c71c8886d7b787d720',
  },
  [getCanonicalPairKey(
    '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
    '0xfe3afec26c59e874f3c1d60b8203cb3852d2bb2aa415df9548b8d688e6683f93::alpha::ALPHA',
    true,
  )]: {
    bluefin: '0xdc2482bdecb5237cba36332d5dea4204fb7df077fbf7b50054d24a678e0f61c9',
    cetus: '0xda7347c3192a27ddac32e659c9d9cbed6f8c9d1344e605c71c8886d7b787d720',
  },
  [getCanonicalPairKey(
    '0x0041f9f9344cac094454cd574e333c4fdb132d7bcc9379bcd4aab485b2a63942::wbtc::WBTC',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0x2a98773f44d34c16c8c9213e56050fdfc04ee210d5b7b7b26b14555ff5643b7f',
  },
  [getCanonicalPairKey(
    '0x2053d08c1e2bd02791056171aab0fd12bd7cd7efad2ab8f6b9c8902f14df2ff2::ausd::AUSD',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0x881639630836b703aa3e04898f8a3740584859838d986619d0ee0f63a784c078',
    cetus: '0x0fea99ed9c65068638963a81587c3b8cafb71dc38c545319f008f7e9feb2b5f8',
  },
  [getCanonicalPairKey(
    '0x27792d9fed7f9844eb4839566001bb6f6cb4804f66aa2da6fe1ee242d896881::coin::COIN',
    '0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN',
  )]: {
    cetus: '0xaa57c66ba6ee8f2219376659f727f2b13d49ead66435aa99f57bb008a64a8042',
  },
  [getCanonicalPairKey(
    '0x27792d9fed7f9844eb4839566001bb6f6cb4804f66aa2da6fe1ee242d896881::coin::COIN',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0x38282481e3a024c50254c31ebfc4710e003fe1b219c0aa31482a860bd58c4ab0',
    cetus: '0xf81d070f24bd2518a28193fc081774654cd8ad145559fa1fa0d7471cb3eecb27',
  },
  [getCanonicalPairKey(
    '0x356a26eb9e012a68958082340d4c4116e7f55615cf27affcff209cf0ae544f59::wal::WAL',
    '0xd1b72982e40348d069bb1ff701e634c117bb5f741f44dff91e472d3b01461e55::stsui::STSUI',
  )]: {
    bluefin: '0xee0d89310b7216a8ef86cd2af0dd22382f4be2049cd073603b7099d9846ab4ca',
  },
  [getCanonicalPairKey(
    '0x356a26eb9e012a68958082340d4c4116e7f55615cf27affcff209cf0ae544f59::wal::WAL',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0xbcc6909d2e85c06cf9cbfe5b292da36f5bfa0f314806474bbf6a0bf9744d37ce',
    cetus: '0x81310e6c4c8726179312c185af0d504eb2cf86a2d1af78a3d362a1b497021c71',
  },
  [getCanonicalPairKey(
    '0x375f70cf2ae4c00bf37117d0c85a2c71545e6ee05c4a5c7d282cd66a4504b068::usdt::USDT',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0x0bd95d012d60190a6713ae51f2d833b24ae70c5fb07fcfb41db40f25549878b1',
    cetus: '0xb8a67c149fd1bc7f9aca1541c61e51ba13bdded64c273c278e50850ae3bff073',
  },
  [getCanonicalPairKey(
    '0x3e8e9423d80e1774a7ca128fccd8bf5f1f7753be658c5e645929037f7c819040::lbtc::LBTC',
    '0xaafb102dd0902f5055cadecd687fb5b71ca82ef0e0285d90afde828ec58ca96b::btc::BTC',
  )]: {
    bluefin: '0x715959c4a67cc6b8d2d4c0db628618d947a032041453a24c3a5315beb613331a',
    cetus: '0x0747352161108a1df5e7c9604037f942aaee4286cb994ad3499a244ad67f399b',
  },
  [getCanonicalPairKey(
    '0x549e8b69270defbfafd4f94e17ec44cdbdd99820b33bda2278dea3b9a32d3f55::cert::CERT',
    '0xa99b8952d4f7d947ea77fe0ecdcc9e5fc0bcab2841d6e2a5aa00c3044e5544b5::navx::NAVX',
  )]: {
    bluefin: '0xa0b4fef70ccef039b94512d6384806979d4c201c5e12af9a4b0458454b80da35',
  },
  [getCanonicalPairKey(
    '0x549e8b69270defbfafd4f94e17ec44cdbdd99820b33bda2278dea3b9a32d3f55::cert::CERT',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0x8f3c373b2a66cfee321768695807e8d823c5a91af184ceaf9310bd12c304b981',
  },
  [getCanonicalPairKey(
    '0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN',
    '0x06864a6f921804860930db6ddbe2e16acdf8504495ea7481637a1c8b9a8fe54b::cetus::CETUS',
  )]: {
    cetus: '0x238f7e4648e62751de29c982cbf639b4225547c31db7bd866982d7d56fc2c7a8',
  },
  [getCanonicalPairKey(
    '0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN',
    '0x960b531667636f39e85867775f52f6b1f220a058c4de786905bdf761e06a56bb::usdy::USDY',
  )]: {
    cetus: '0x0e809689d04d87f4bd4e660cd1b84bf5448c5a7997e3d22fc480e7e5e0b3f58d',
  },
  [getCanonicalPairKey(
    '0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN',
    '0xaf8cd5edc19c4512f4259f0bee101a40d41ebed738ade5874359610ef8eeced5::coin::COIN',
  )]: {
    cetus: '0x5b0b24c27ccf6d0e98f3a8704d2e577de83fa574d3a9060eb8945eeb82b3e2df',
  },
  [getCanonicalPairKey(
    '0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN',
    '0xb7844e289a8410e50fb3ca48d69eb9cf29e27d223ef90353fe1bd8e27ff8f3f8::coin::COIN',
  )]: {
    cetus: '0x9ddb0d269d1049caf7c872846cc6d9152618d1d3ce994fae84c1c051ee23b179',
  },
  [getCanonicalPairKey(
    '0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN',
    '0xc060006111016b8a020ad5b33834984a437aaa7d3c74c18e09a95d48aceab08c::coin::COIN',
  )]: {
    cetus: '0xc8d7a1503dc2f9f5b05449a87d8733593e2f0f3e7bffd90541252782e4d2ca20',
  },
  [getCanonicalPairKey(
    '0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN',
    '0xce7ff77a83ea0cb6fd39bd8748e2ec89a3f41e8efdc3f4eb123e0ca37b184db2::buck::BUCK',
  )]: {
    cetus: '0x81fe26939ed676dd766358a60445341a06cea407ca6f3671ef30f162c84126d5',
  },
  [getCanonicalPairKey(
    '0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    cetus: '0x1efc96c99c9d91ac0f54f0ca78d2d9a6ba11377d29354c0a192c86f0495ddec7',
  },
  [getCanonicalPairKey(
    '0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN',
    '0xfe3afec26c59e874f3c1d60b8203cb3852d2bb2aa415df9548b8d688e6683f93::alpha::ALPHA',
  )]: {
    cetus: '0x0cbe3e6bbac59a93e4d358279dff004c98b2b8da084729fabb9831b1c9f71db6',
  },
  [getCanonicalPairKey(
    '0x77045f1b9f811a7a8fb9ebd085b5b0c55c5cb0d1520ff55f7037f89b5da9f5f1::TBTC::TBTC',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0x1f121fb96bb1f57ac07564e7fad3a0412a6958701da1a66496b70f7ea15e051e',
  },
  [getCanonicalPairKey(
    '0x876a4b7bce8aeaef60464c11f4026903e9afacab79b9b142686158aa86560b50::xbtc::XBTC',
    '0x9d297676e7a4b771ab023291377b2adfaa4938fb9080b8d12430e4b108b836a9::xaum::XAUM',
  )]: {
    bluefin: '0xa873b036fa735c40b776a40dffdd1134ec4e24d4bbe8ae28de6bcc2a03ac4d81',
  },
  [getCanonicalPairKey(
    '0x876a4b7bce8aeaef60464c11f4026903e9afacab79b9b142686158aa86560b50::xbtc::XBTC',
    '0xaafb102dd0902f5055cadecd687fb5b71ca82ef0e0285d90afde828ec58ca96b::btc::BTC',
  )]: {
    bluefin: '0x6490f12f357a95dd5cb2415258efc3377a73ef0979a3f785a05ab67351ed4a98',
    cetus: '0xd56943aba8e5951e1e22d9ad18195f9358a2c63080bc0c2e577339ffea5e483b',
  },
  [getCanonicalPairKey(
    '0x876a4b7bce8aeaef60464c11f4026903e9afacab79b9b142686158aa86560b50::xbtc::XBTC',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0x1b0cc1c66185ceb8eccbc807c73243ce957f0053dfa1026149265bb2ff704a07',
  },
  [getCanonicalPairKey(
    '0x9d297676e7a4b771ab023291377b2adfaa4938fb9080b8d12430e4b108b836a9::xaum::XAUM',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0x458fc3722cc88babd7cbe78273aa5e4ecbdff75c76a2ad14cd1f75418b569649',
    mmt: '0xc5bdc685b8006071938b5cb94103dc873c9946578d717c9b5b67fc264ff941e0',
  },
  [getCanonicalPairKey(
    '0xa99b8952d4f7d947ea77fe0ecdcc9e5fc0bcab2841d6e2a5aa00c3044e5544b5::navx::NAVX',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0x6666b67759ec9cfcfecf553e4cb60d0efcc2015a4fddb8e3406719e9d21f3427',
  },
  [getCanonicalPairKey(
    '0xaafb102dd0902f5055cadecd687fb5b71ca82ef0e0285d90afde828ec58ca96b::btc::BTC',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0xf0e4772e80800550368973d1f8ab2c9a7241ace8df8770452ee2bf3e3e67b8a1',
    cetus: '0xa72776082624b0f5da55e385107fc0176114bfea5b281b880acae505a9bd1f1a',
  },
  [getCanonicalPairKey(
    '0xb45fcfcc2cc07ce0702cc2d229621e046c906ef14d9b25e8e4d25f6e8763fef7::send::SEND',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0xbd5b29a952040ccd47ce2822bddd4aba3affaae9d6ccdaf65aded5528e39b837',
    cetus: '0x19eded65f7d310e3d9c659f6566087a28d02bc5e12db3bb34a69daa7ca5ae56a',
  },
  [getCanonicalPairKey(
    '0xc060006111016b8a020ad5b33834984a437aaa7d3c74c18e09a95d48aceab08c::coin::COIN',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0x0321b68a0fca8c990710d26986ba433d06b351deba9384017cd6175f20466a8f',
    cetus: '0x6bd72983b0b5a77774af8c77567bb593b418ae3cd750a5926814fcd236409aaa',
  },
  [getCanonicalPairKey(
    '0xce7ff77a83ea0cb6fd39bd8748e2ec89a3f41e8efdc3f4eb123e0ca37b184db2::buck::BUCK',
    '0xd1b72982e40348d069bb1ff701e634c117bb5f741f44dff91e472d3b01461e55::stsui::STSUI',
  )]: {
    bluefin: '0x0bc35f5b7e7b77dadc62c2630e9efafb1beb4122fd5393bf3b99586abf3ca8b1',
  },
  [getCanonicalPairKey(
    '0xce7ff77a83ea0cb6fd39bd8748e2ec89a3f41e8efdc3f4eb123e0ca37b184db2::buck::BUCK',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    cetus: '0x4c50ba9d1e60d229800293a4222851c9c3f797aa5ba8a8d32cc67ec7e79fec60',
  },
  [getCanonicalPairKey(
    '0xd0e89b2af5e4910726fbcd8b8dd37bb79b29e5f83f7491bca830e94f7f226d29::eth::ETH',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    cetus: '0x9e59de50d9e5979fc03ac5bcacdb581c823dbd27d63a036131e17b391f2fac88',
  },
  [getCanonicalPairKey(
    '0xd1b72982e40348d069bb1ff701e634c117bb5f741f44dff91e472d3b01461e55::stsui::STSUI',
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
  )]: {
    bluefin: '0x151d6959cb2a6d1a5b6cfec6d1eae690af0318e46e5fb3ec45dd4e3b67eebeda',
  },
  [getCanonicalPairKey(
    '0xd1b72982e40348d069bb1ff701e634c117bb5f741f44dff91e472d3b01461e55::stsui::STSUI',
    '0xe44df51c0b21a27ab915fa1fe2ca610cd3eaa6d9666fe5e62b988bf7f0bd8722::musd::MUSD',
  )]: {
    bluefin: '0x0da4bcb1669ae3b6ce80f024e3a2076e2c4e2cc899d4724fce94da0f729bc968',
  },
  [getCanonicalPairKey(
    '0xd1b72982e40348d069bb1ff701e634c117bb5f741f44dff91e472d3b01461e55::stsui::STSUI',
    '0xfe3afec26c59e874f3c1d60b8203cb3852d2bb2aa415df9548b8d688e6683f93::alpha::ALPHA',
  )]: {
    bluefin: '0xd4051b5dc76ca354e48813268aa79de38b274878ef6a9d274066ae5a47f46cc6',
  },
  [getCanonicalPairKey(
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
    '0xdeeb7a4662eec9f2f3def03fb937a663dddaa2e215b8078a284d026b7946c270::deep::DEEP',
  )]: {
    bluefin: '0xd5e3a3c7396702d8f358a63ef921cc7c1951f52c6dfc2051cc8772cf7cb9900c',
  },
  [getCanonicalPairKey(
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
    '0xe1b45a0e641b9955a20aa0ad1c1f4ad86aad8afb07296d4085e349a50e90bdca::blue::BLUE',
  )]: {
    bluefin: '0x3717c637003c4274f20cde8c4eeadbffa2bbf16d995a0fe0f7bf99c03cf52e61',
    cetus: '0xab9806a212de1355936cd88314d0539769baab27dc08f3169f35adbf9a188764',
  },
  [getCanonicalPairKey(
    '0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC',
    '0xfe3afec26c59e874f3c1d60b8203cb3852d2bb2aa415df9548b8d688e6683f93::alpha::ALPHA',
  )]: {
    bluefin: '0x6595edf6d8c8b6894a5c6760843ae2fde81cb37d8586984dd1345b0f00bfecd8',
    cetus: '0x29e218b46e35b4cf8eedc7478b8795d2a9bcce9c61e11101b3a039ec93305126',
  },
  [getCanonicalPairKey(
    '0xdeeb7a4662eec9f2f3def03fb937a663dddaa2e215b8078a284d026b7946c270::deep::DEEP',
    '0xe1b45a0e641b9955a20aa0ad1c1f4ad86aad8afb07296d4085e349a50e90bdca::blue::BLUE',
  )]: {
    bluefin: '0x4b8271fc4819078e44ee9a0506a824b77464789d57ace355d0562a4776c51840',
    cetus: '0x63fc1f6213038a07b77716b1ab44e90eb1bcf8ad02ea5c6a70c53f8fdc27a2ad',
  },
};
